name: Run Yellow Pages Scraper

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Run the workflow when code is pushed to the main branch

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 aiohttp openpyxl

      - name: Run Yellow Pages scraper
        run: |
          python yellow-pages.py

      - name: Upload output files
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: scraped-data
          path: |
            *.csv # Upload all generated CSV files as artifacts
